# Generated by Django 5.2.5 on 2025-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reassigned',
            field=models.BooleanField(default=False),
        ),
    ]
