# Generated by Django 5.2.5 on 2025-08-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_complaint_reassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='reassigned',
        ),
    ]
