# Generated by Django 5.2.5 on 2025-08-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_complaint_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('not_closed', 'Not Closed')], default='STATUS_PENDING', max_length=12),
        ),
    ]
